# Nama      : Brian Mohamad Safiudin
# NIM       : 2141720133
# Kelas     : TI - 3F

---
# **Praktikum 4 - Pertemuan 9**
---
Pada praktikum kali ini, Anda diminta untuk membuat model ANN untuk mengklasifikasi potensi seorang customer akan meninggalkan perusahaan Anda atau tidak. Istirlah populer dari fenomena ini disebut sebagai 'churn'. Tingkat churn yang tinggi (chrun rate) akan berdampak tidak baik bagi perusahaan.

---
# **Langkah 1 - Import Library**
---

In [2]:
pip install --upgrade pip

  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   - -------------------------------------- 0.1/2.1 MB 1.7 MB/s eta 0:00:02
   --- ------------------------------------ 0.2/2.1 MB 2.5 MB/s eta 0:00:01
   -------- ------------------------------- 0.5/2.1 MB 3.6 MB/s eta 0:00:01
   ----------- ---------------------------- 0.6/2.1 MB 3.5 MB/s eta 0:00:01
   ---------------- ----------------------- 0.9/2.1 MB 4.2 MB/s eta 0:00:01
   ------------------- -------------------- 1.0/2.1 MB 3.8 MB/s eta 0:00:01
   ---------------------- ----------------- 1.2/2.1 MB 3.9 MB/s eta 0:00:01
   ---------------------- ----------------- 1.2/2.1 MB 3.9 MB/s eta 0:00:01
   -------------------------- ------------- 1.4/2.1 MB 3.4 MB/s eta 0:00:01
   --------------------------- ------------ 1.4/2.1 MB 

In [3]:
pip install tensorflow

     ---------------------------------------- 0.0/57.5 kB ? eta -:--:--
     ----------------------------------- ---- 51.2/57.5 kB 2.7 MB/s eta 0:00:01
     ---------------------------------------- 57.5/57.5 kB 1.0 MB/s eta 0:00:00
     ---------------------------------------- 0.0/65.5 kB ? eta -:--:--
     ---------------------------------------- 65.5/65.5 kB 1.8 MB/s eta 0:00:00
     ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
     --- ------------------------------------ 0.1/1.5 MB 6.4 MB/s eta 0:00:01
     ----- ---------------------------------- 0.2/1.5 MB 2.5 MB/s eta 0:00:01
     ----------- ---------------------------- 0.4/1.5 MB 3.2 MB/s eta 0:00:01
     ----------------- ---------------------- 0.7/1.5 MB 3.8 MB/s eta 0:00:01
     ------------------- -------------------- 0.7/1.5 MB 3.3 MB/s eta 0:00:01
     ------------------------ --------------- 0.9/1.5 MB 3.4 MB/s eta 0:00:01
     --------------------------- ------------ 1.0/1.5 MB 3.2 MB/s eta 0:00:01

In [4]:
# Import library
import numpy as np
import pandas as pd
import tensorflow as tf

---
# **Langkah 2 - Load Data**
---

In [6]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

# Cek data
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


---
# **Langkah 3 - Encoding Data Kategorikal**
---

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

# Cek data
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


---
# **Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder**
---

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

# Cek data
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


---
# **Langkah 5 - Split Data**
---

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

---
# **Langkah 6 - Scaling Fitur**
---

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# **Membuat Model ANN**
---
Artificial Neural Network adalah jenis model komputasi yang terinspirasi oleh struktur jaringan saraf dalam otak manusia. 

---
# **Langkah 1 - Inisiasi Model ANN**
---

In [12]:
ann = tf.keras.models.Sequential()

---
# **Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama**
---

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

---
# **Langkah 3 - Membuat Hidden Layer Kedua**
---

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

---
# **Langkah 4 - Membuat Output Laye**
---

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

---
# **Training Model**
---
Model diberikan data pelatihan dan algoritma belajar untuk memahami hubungan dalam data. Ini melibatkan pengoptimalan parameter model agar dapat membuat prediksi yang akurat.

---
# **Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN**
---

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

---
# **Langkah 2 - Fitting Model**
---

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5930 - accuracy: 0.7372
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4935 - accuracy: 0.7959
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4507 - accuracy: 0.8026
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4319 - accuracy: 0.8129
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4223 - accuracy: 0.8171
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4144 - accuracy: 0.8201
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4069 - accuracy: 0.8223
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3989 - accuracy: 0.8263
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3890 - accuracy: 0.8319
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3708 - accura

---
# **Membuat Prediksi**
---
Diberikan informasi sebagai berikut,
- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: 60000
- Number of Products: 2
- Does this customer have a credit card ? Yes
- Is this customer an Active Member: Yes
- Estimated Salary: 50000

##### Apakah customer tersebut perlu dipertahankan?

---
# **Modelkan Data Baru dan Buat Prediksi**
---

In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 149ms/step
[[False]]


---
# **Prediksi Dengan Data Testing**
---

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


---
# **Cek Akurasi dan Confusion Matrix**
---

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 198  207]]


0.8615