**TUGAS PRAKTIKUM**
1. Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
2. Anda diperbolehkan melakukan eksplorasi terhadap,
  - Metode pra pengolahan
  - Pemilihan fitur
  - Arsitektur ANN
  - Fungsi Aktiviasi
3. ANN diimplementasikan dengan menggunakan tensowflow
4. JELASKAN HASIL YANG ANDA DAPATKAN.
  - AKURASI
  - CONFUSION MATRIX
  - KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

**Langkah 1 - Impor Library**


In [1]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix

In [2]:
data_mnist = fetch_openml('mnist_784', version=1, parser='auto')

**Langkah 2 - Eksplorasi Dataset**

In [3]:
# Melihat dimensi data
print("Jumlah sampel MNIST:", data_mnist.data.shape[0])  # Jumlah sampel
print("Dimensi setiap sampel MNIST:", data_mnist.data.shape[1])  # Dimensi setiap sampel
print("Jumlah kelas MNIST:", len(set(data_mnist.target)))  # Jumlah kelas

Jumlah sampel MNIST: 70000
Dimensi setiap sampel MNIST: 784
Jumlah kelas MNIST: 10


In [4]:
# mengambil data dan label
X = data_mnist.data.astype('float32')
y = data_mnist.target.astype('int')

In [5]:
X.shape

(70000, 784)

In [6]:
# scaling data menggunakan MinMaxScaler
scaler = MinMaxScaler()
X_scalling = scaler.fit_transform(X)

In [7]:
print(X_scalling[:5])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


**Langkah 3 - Ekstraksi Fitur dan Split Data**

In [8]:
pca = PCA(n_components=200)
X_pca = pca.fit_transform(X_scalling)

In [9]:
# Split dataset menjadi data pelatihan dan data pengujian
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size = 0.2, random_state = 42)

**Langkah 4 - Membangun Model ANN**

In [10]:
# Membuat model ANN
model = Sequential()

# Tambahkan lapisan input
model.add(Dense(units=128, activation='relu', input_dim=200))  # 128 unit pada lapisan tersembunyi pertama

# Tambahkan lapisan tersembunyi pertama
model.add(Dense(units=64, activation='relu'))  # 64 unit pada lapisan tersembunyi kedua

# Tambahkan lapisan tersembunyi kedua
model.add(Dense(units=32, activation='relu'))  # 32 unit pada lapisan tersembunyi ketiga

# Tambahkan lapisan output
model.add(Dense(units=10, activation='softmax'))  # 10 unit pada lapisan output untuk klasifikasi 10 kelas

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               25728     
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 10)                330       
                                                                 
Total params: 36394 (142.16 KB)
Trainable params: 36394 (142.16 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


**Langkah 5 - Training Model**

In [11]:
# Kompilasi model ANN
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [12]:
# Melatih model menggunakan data pelatihan
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)  # Contoh menggunakan 10 epoch dan ukuran batch 32

# Evaluasi model menggunakan data pengujian
loss, accuracy = model.evaluate(X_test, y_test)
print("Loss:", loss)
print("Accuracy:", accuracy)

Epoch 1/10
1400/1400 [==============================] - 7s 4ms/step - loss: 0.3044 - accuracy: 0.9125 - val_loss: 0.1539 - val_accuracy: 0.9524
Epoch 2/10
1400/1400 [==============================] - 8s 6ms/step - loss: 0.1018 - accuracy: 0.9683 - val_loss: 0.1095 - val_accuracy: 0.9663
Epoch 3/10
1400/1400 [==============================] - 8s 6ms/step - loss: 0.0593 - accuracy: 0.9816 - val_loss: 0.1186 - val_accuracy: 0.9655
Epoch 4/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0411 - accuracy: 0.9873 - val_loss: 0.1106 - val_accuracy: 0.9681
Epoch 5/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0285 - accuracy: 0.9906 - val_loss: 0.1232 - val_accuracy: 0.9677
Epoch 6/10
1400/1400 [==============================] - 5s 3ms/step - loss: 0.0257 - accuracy: 0.9909 - val_loss: 0.1352 - val_accuracy: 0.9660
Epoch 7/10
1400/1400 [==============================] - 7s 5ms/step - loss: 0.0189 - accuracy: 0.9932 - val_loss: 0.1289 - val_accuracy:

**Langkah 6 - Evaluasi**

In [13]:
# Evaluasi model pada data pelatihan
train_loss, train_accuracy = model.evaluate(X_train, y_train)
print("Train Loss:", train_loss)
print("Train Accuracy:", train_accuracy)

1750/1750 [==============================] - 4s 2ms/step - loss: 0.0360 - accuracy: 0.9916
Train Loss: 0.035982392728328705
Train Accuracy: 0.991553544998169


In [14]:
# Evaluasi model pada data pengujian
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

438/438 [==============================] - 1s 2ms/step - loss: 0.1590 - accuracy: 0.9681
Test Loss: 0.15898793935775757
Test Accuracy: 0.9680714011192322


In [15]:
# Melakukan prediksi menggunakan model pada data pengujian
predictions = model.predict(X_test)

# Mengubah prediksi dari format one-hot encoded ke kelas
predicted_classes = np.argmax(predictions, axis=1)

# Menghitung confusion matrix
confusion_mtx = confusion_matrix(y_test, predicted_classes)

print("Confusion Matrix:")
print(confusion_mtx)

438/438 [==============================] - 1s 2ms/step
Confusion Matrix:
[[1319    0    6    0    0    4    5    1    5    3]
 [   1 1576    4    5    2    0    1    4    4    3]
 [   3    3 1335    3    1    3    6    9   10    7]
 [   0    1   14 1383    0   16    0    7    6    6]
 [   2    2    4    1 1233    3    6    4    4   36]
 [   2    1    0   23    0 1228    3    0   11    5]
 [   6    1    2    0    4    9 1368    0    6    0]
 [   4    5   13    4    1    4    0 1445    0   27]
 [   4    7    2   17    0    9    6    4 1297   11]
 [   5    2    2   11    9    5    0    9    8 1369]]
