Langkah 1 - Import Library

In [3]:
%pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf

Langkah 2 - Load Data

In [5]:
# Membaca dataset dari file 'Churn_Modelling.csv' menggunakan pandas dan menyimpannya ke dalam variabel dataset
dataset = pd.read_csv('Churn_Modelling.csv')

# Memilih fitur dari dataset (kolom 4 hingga kolom sebelum terakhir) dan mengkonversinya ke dalam larik (array) numpy
X = dataset.iloc[:, 3:-1].values
# Variabel X akan berisi fitur atau atribut dari dataset yang akan digunakan untuk prediksi

# Memilih label atau target dari dataset (kolom terakhir) dan mengkonversinya ke dalam larik (array) numpy
y = dataset.iloc[:, -1].values
# Variabel y akan berisi label atau target yang akan diprediksi oleh model

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


Langkah 3 - Encoding Data Kategorikal

In [7]:
from sklearn.preprocessing import LabelEncoder

# Mengimpor LabelEncoder dari modul sklearn.preprocessing
# LabelEncoder digunakan untuk mengubah nilai pada suatu kolom menjadi nilai numerik

le = LabelEncoder()  # Membuat objek LabelEncoder

# Mengubah nilai pada kolom ke-2 dari array X ke nilai numerik
# Fungsi fit_transform dari LabelEncoder digunakan untuk mengubah nilai pada kolom tertentu menjadi nilai numerik
X[:, 2] = le.fit_transform(X[:, 2])

# Kolom ke-2 diubah menjadi nilai numerik dan disimpan kembali ke array X
# Nilai yang semula kategorikal diubah menjadi representasi numerik


In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Mengimpor ColumnTransformer dan OneHotEncoder dari modul sklearn.compose dan sklearn.preprocessing

# Membuat objek ColumnTransformer untuk mentransformasi kolom kategorikal menjadi representasi numerik
# transformers parameter menyediakan informasi tentang transformasi yang akan dilakukan
# ('encoder', OneHotEncoder(), [1]) menunjukkan bahwa kolom ke-1 akan diubah menjadi representasi one-hot encoding
# remainder='passthrough' mengindikasikan bahwa kolom yang tidak diubah akan dilewatkan tanpa perubahan
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

# Melakukan transformasi terhadap array X menggunakan ColumnTransformer yang telah dibuat
# Hasil transformasi disimpan kembali ke dalam array X
X = np.array(ct.fit_transform(X))


In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Langkah 5 - Split Data

In [11]:
from sklearn.model_selection import train_test_split

# Mengimpor fungsi train_test_split dari modul sklearn.model_selection

# Memisahkan dataset menjadi data latih (train) dan data uji (test)
# X adalah dataset fitur, y adalah dataset target
# test_size=0.2 menunjukkan proporsi data yang akan digunakan untuk data uji (20% dari total data)
# random_state=0 digunakan untuk memberikan keacakan yang sama pada pembagian setiap kali program dijalankan
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Data dibagi menjadi X_train (fitur latih), X_test (fitur uji), y_train (label latih), y_test (label uji)
# X_train dan y_train adalah data yang akan digunakan untuk melatih model
# X_test dan y_test adalah data yang akan digunakan untuk menguji kinerja model yang telah dilatih


Langkah 6 - Scaling Fitur

In [12]:
from sklearn.preprocessing import StandardScaler

# Importing the StandardScaler from the sklearn.preprocessing module

sc = StandardScaler()  # Creating an instance of StandardScaler

# Standardizing (scaling) the features in the training set
# fit_transform function scales the training set features
X_train = sc.fit_transform(X_train)

# Using the mean and standard deviation obtained from the training set to transform the test set
# transform function applies the same transformation to the test set features
X_test = sc.transform(X_test)


# Membuat Model ANN

Langkah 1 - Inisiasi Model ANN

In [15]:
ann = tf.keras.models.Sequential()

Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama

In [16]:
# Menambahkan lapisan Dense ke dalam model neural network (ANN)
# 'ann' mungkin merupakan objek model neural network yang telah dibuat sebelumnya
# 'Dense' mengindikasikan bahwa setiap neuron dalam lapisan ini terhubung dengan setiap neuron pada lapisan sebelumnya
# 'units=6' menunjukkan bahwa lapisan memiliki 6 neuron
# 'activation='relu'' menunjukkan penggunaan fungsi aktivasi ReLU pada lapisan tersebut
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Langkah 3 - Membuat Hidden Layer Kedua

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Langkah 4 - Membuat Output Layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training Model

Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN

In [19]:
# Compile model Jaringan Saraf Tiruan (ANN)
# 'ann' merupakan model jaringan saraf yang telah dibuat sebelumnya

# Menggunakan optimizer 'adam' untuk melakukan optimisasi model selama pelatihan
# Loss function 'binary_crossentropy' digunakan untuk mengukur perbedaan distribusi probabilitas pada masalah klasifikasi biner
# Metrics yang diukur selama pelatihan adalah 'accuracy', yang mengindikasikan tingkat keakuratan model

ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

Langkah 2 - Fitting Model

In [20]:
# Melatih (fit) model Jaringan Saraf Tiruan (ANN) dengan data latih
# 'ann' adalah model jaringan saraf yang akan dilatih

# X_train adalah data fitur (fitur latih), y_train adalah label atau target (label latih)
# Proses pelatihan dilakukan dengan batch_size=32, di mana data dibagi menjadi batch-batch kecil
# Epochs=100 menunjukkan jumlah iterasi atau putaran data selama pelatihan model

ann.fit(X_train, y_train, batch_size=32, epochs=100)


Epoch 1/100
250/250 [==============================] - 3s 4ms/step - loss: 0.6609 - accuracy: 0.6314
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4810 - accuracy: 0.7959
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4424 - accuracy: 0.8037
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4256 - accuracy: 0.8138
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4161 - accuracy: 0.8188
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4093 - accuracy: 0.8192
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4031 - accuracy: 0.8241
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3959 - accuracy: 0.8299
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3864 - accuracy: 0.8361
Epoch 10/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3766 - accura

## Membuat Prediksi
Diberikan informasi sebagai berikut,
- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: $ 60000
- Number of Products: 2
- Does this customer have a credit card ? Yes
- Is this customer an Active Member: Yes
- Estimated Salary: $ 50000

Apakah customer tersebut perlu dipertahankan?


Modelkan Data Baru dan Buat Prediksi

In [21]:
# Melakukan prediksi menggunakan model Jaringan Saraf Tiruan (ANN) terhadap data yang diubah skala (scaled data)
# 'ann' adalah model jaringan saraf yang telah dilatih sebelumnya

# Data diubah menggunakan StandardScaler (sc.transform) agar sesuai dengan skala yang digunakan selama pelatihan
# Setelah dilakukan prediksi, perbandingan dilakukan apakah nilai prediksi lebih besar dari 0.5

prediction = ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5
print(prediction)

1/1 [==============================] - 0s 310ms/step
[[False]]


Apakah hasilnya False?

Jawab: Ya, Hasilnya False

Prediksi Dengan Data Testing

In [22]:
# Melakukan prediksi terhadap data uji menggunakan model Jaringan Saraf Tiruan (ANN)
y_pred = ann.predict(X_test)

# Menggunakan ambang batas 0.5 untuk mengklasifikasikan hasil prediksi sebagai True atau False
y_pred = (y_pred > 0.5)

# Mencetak hasil prediksi dan nilai sebenarnya dalam satu kolom
# Menggabungkan hasil prediksi dengan nilai sebenarnya dari data uji (y_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Cek Akurasi dan Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Membuat confusion matrix (matriks kebingungan) untuk mengevaluasi performa model
# y_test adalah nilai sebenarnya dari data uji, y_pred adalah hasil prediksi
cm = confusion_matrix(y_test, y_pred)

# Mencetak matriks kebingungan (confusion matrix)
print(cm)

# Menghitung dan mencetak nilai akurasi dari model
# Membandingkan hasil prediksi (y_pred) dengan nilai sebenarnya (y_test)
accuracy_score(y_test, y_pred)


[[1508   87]
 [ 190  215]]


0.8615