Import Library dan Persiapan Data

In [2]:
import tensorflow as tf
from keras import layers, models
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

# Unduh dataset MNIST dari scikit-learn
mnist = fetch_openml('mnist_784')

# Pisahkan data gambar dan label
images = mnist.data.astype('float32')
labels = mnist.target.astype('int')

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


1. pre-processing

In [3]:
images /= 255.0  # Skalakan data

# Bagi data menjadi data pelatihan dan pengujian
train_images, test_images, train_labels, test_labels = train_test_split(
    images, labels, test_size=0.2, random_state=42)

In [4]:
model = models.Sequential([
    layers.Reshape(target_shape=(28, 28, 1), input_shape=(784,)), #engubah bentuk input dari vektor 1D (784 elemen) menjadi matriks 3D (28x28x1). 
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)), #Menambahkan lapisan konvolusi dengan 32 filter, masing-masing berukuran 3x3, dan fungsi aktivasi ReLU.
    layers.MaxPooling2D((2, 2)), #Menambahkan lapisan max pooling dengan ukuran jendela 2x2.
    layers.Flatten(), #Mengubah output dari lapisan sebelumnya (berupa matriks) menjadi vektor 1D.
    layers.Dense(128, activation='relu'), #Menambahkan lapisan terhubung penuh (fully connected) dengan 128 neuron dan fungsi aktivasi ReLU.
    layers.Dense(64, activation='relu'), #Menambahkan lapisan terhubung penuh dengan 64 neuron dan fungsi aktivasi ReLU.
    layers.Dense(10, activation='softmax') #Menambahkan lapisan terhubung penuh dengan 10 neuron (sesuai dengan jumlah kelas digit) dan fungsi aktivasi softmax.
])

In [5]:
model.compile(optimizer='adam', #mengoptimalkan proses pelatihan
              loss='sparse_categorical_crossentropy', # Memilih fungsi kerugian untuk masalah klasifikasi dengan banyak kelas.
              metrics=['accuracy']) #Menggunakan metrik akurasi untuk memantau kinerja model s

In [6]:
history = model.fit(train_images, train_labels,
                    epochs=10, validation_split=0.2)

Epoch 1/10
1400/1400 [==============================] - 70s 48ms/step - loss: 0.1855 - accuracy: 0.9434 - val_loss: 0.0881 - val_accuracy: 0.9724
Epoch 2/10
1400/1400 [==============================] - 76s 54ms/step - loss: 0.0604 - accuracy: 0.9811 - val_loss: 0.0579 - val_accuracy: 0.9814
Epoch 3/10
1400/1400 [==============================] - 75s 54ms/step - loss: 0.0395 - accuracy: 0.9875 - val_loss: 0.0751 - val_accuracy: 0.9778
Epoch 4/10
1400/1400 [==============================] - 75s 53ms/step - loss: 0.0255 - accuracy: 0.9915 - val_loss: 0.0566 - val_accuracy: 0.9846
Epoch 5/10
1400/1400 [==============================] - 70s 50ms/step - loss: 0.0187 - accuracy: 0.9936 - val_loss: 0.0529 - val_accuracy: 0.9844
Epoch 6/10
1400/1400 [==============================] - 71s 51ms/step - loss: 0.0144 - accuracy: 0.9956 - val_loss: 0.0663 - val_accuracy: 0.9828
Epoch 7/10
1400/1400 [==============================] - 74s 53ms/step - loss: 0.0115 - accuracy: 0.9960 - val_loss: 0.0601 -

In [7]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Akurasi pada data pengujian: {test_acc:.2f}')

438/438 [==============================] - 6s 12ms/step - loss: 0.0759 - accuracy: 0.9844
Akurasi pada data pengujian: 0.98


In [8]:
# Evaluasi akurasi data pelatihan
train_loss, train_acc = model.evaluate(train_images, train_labels)
print(f'Akurasi pada data pelatihan: {train_acc:.2f}')

1750/1750 [==============================] - 21s 12ms/step - loss: 0.0213 - accuracy: 0.9943
Akurasi pada data pelatihan: 0.99


In [9]:
from sklearn.metrics import confusion_matrix

# Membuat prediksi pada data pengujian
predictions = model.predict(test_images)
predicted_labels = np.argmax(predictions, axis=1)

# Membuat matriks kebingungan
confusion = confusion_matrix(test_labels, predicted_labels)
print('Matriks Kebingungan:')
print(confusion)

438/438 [==============================] - 6s 12ms/step
Matriks Kebingungan:
[[1332    2    0    1    0    0    3    3    1    1]
 [   0 1591    1    1    0    1    0    5    1    0]
 [   1   11 1338    6    0    0    0   16    7    1]
 [   1    3    2 1418    0    1    0    3    4    1]
 [   0    0    0    0 1287    0    0    4    0    4]
 [   0    3    1   19    0 1239    5    1    5    0]
 [   1    6    1    0    4    1 1382    0    1    0]
 [   1    1    5    1    0    0    0 1494    0    1]
 [   1    7    1    5    0    2    4   10 1323    4]
 [   4    2    0    7    9    2    0   17    2 1377]]
