# **TUGAS**

1. Buatlah model klasifikasi dengan menggunakan SVM untuk data suara, voice.csv. 
2. Buatlah model klasfikasi Multinomial Naive Bayes dengan ketentuan,
    1. Menggunakan data spam.csv
    2. Fitur CountVectorizer dengan mengaktifkan stop_words
    3. Evaluasi hasilnya
3. Buatlah model klasfikasi Multinomial Naive Bayes dengan ketentuan,
    1. Menggunakan data spam.csv
    2. Fitur TF-IDF dengan mengaktifkan stop_words
    3. Evaluasi hasilnya dan bandingkan dengan hasil pada Tugas no 2.
    4. Berikan kesimpulan fitur mana yang terbaik pada kasus data spam.csv

**Impor Library**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn import datasets
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# **1. Buatlah model klasifikasi dengan menggunakan SVM untuk data suara, voice.csv.**

In [8]:
# Baca data dari file CSV
data = pd.read_csv('voice.csv')

# Pisahkan fitur dan label
X = data.drop('label', axis=1)
y = data['label']

# Jika label string, konversi ke numerik
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

data.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [9]:
# Bagi dataset menjadi data pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalisasi data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Buat model SVM
svm_model = SVC(kernel='linear', C=1.0, random_state=42)

# Latih model
svm_model.fit(X_train, y_train)

# Evaluasi model
y_pred = svm_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f'Accuracy: {accuracy:.2f}')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.98
              precision    recall  f1-score   support

           0       0.96      0.99      0.98       297
           1       0.99      0.97      0.98       337

    accuracy                           0.98       634
   macro avg       0.98      0.98      0.98       634
weighted avg       0.98      0.98      0.98       634

[[293   4]
 [ 11 326]]


**Akurasi Model SVM thdap lebel sebenarnya dan prrediksi**

In [10]:
# Hitung akurasi
accuracy = accuracy_score(y_test, y_pred)

# print hasil akurasi
print(f'Skor Akurasi : {int(accuracy * 100)}%')


Skor Akurasi : 97%


# **2. Buatlah model klasfikasi Multinomial Naive Bayes dengan ketentuan**

**Menggunakan data spam.csv**

In [12]:
# baca file CSV
ds = pd.read_csv('spam.csv', encoding='latin-1') 
ds.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [13]:
# Drop 3 kolom NaN
ds = ds.drop(ds.iloc[:,2:], axis=1)

# beri nama v1 dan v2
new_cols = {
    'v1': 'Labels',
    'v2': 'Message'
}

# berinama  v1 dan v2
ds = ds.rename(columns=new_cols)

# cek data
ds.head()

Labels                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [14]:
# Melakukan encoding kategori
ds['Labels'] = ds['Labels'].map({'ham': 0, 'spam': 1})

# Memisahkan fitur dan target
X = ds['Message'].values
y = ds['Labels'].values

**Fitur CountVectorizer dengan mengaktifkan stop_words**

In [15]:
# bagi data training (80%) dan data testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.pipeline import Pipeline

# Membuat pipeline dengan CountVectorizer dan Multinomial Naive Bayes
pipeline = Pipeline([
    ('vectorizer', CountVectorizer(stop_words='english')),
    ('classifier', MultinomialNB())
])

# Melatih model
pipeline.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer(stop_words='english')),
                ('classifier', MultinomialNB())])

**Evaluasi Hasil**


In [17]:
# Memprediksi label untuk data pengujian
y_pred = pipeline.predict(X_test)

# Mengukur akurasi model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi Model Multinomial:", accuracy)

# Menampilkan laporan klasifikasi
print("Hasil Klasifikasi:")
print(classification_report(y_test, y_pred))

# Menampilkan matriks konfusi
print("Matriks Konfusi:")
print(confusion_matrix(y_test, y_pred))

Akurasi Model Multinomial: 0.9838565022421525
Hasil Klasifikasi:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       965
           1       0.96      0.92      0.94       150

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

Matriks Konfusi:
[[959   6]
 [ 12 138]]


# **3. Buatlah model klasfikasi Multinomial Naive Bayes**

In [19]:
# baca file CSV
ds = pd.read_csv('spam.csv', encoding='latin-1') 

# Drop 3 kolom NaN
ds = ds.drop(ds.iloc[:,2:], axis=1)

# beri nama v1 dan v2
new_cols = {
    'v1': 'Labels',
    'v2': 'Message'
}

# berinama  v1 dan v2
ds = ds.rename(columns=new_cols)

# cek data
ds.head()


Labels                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [20]:
# Melakukan encoding kategori
ds['Labels'] = ds['Labels'].map({'ham': 0, 'spam': 1})

# Memisahkan fitur dan target
X = ds['Message'].values
y = ds['Labels'].values

**mengaktifkan stop_words FITUR TF-IDF**

In [21]:
# Membagi data training (80%) dan data testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

**Model Multinomial Naive Bayes dengan TF-IDF Vectorizer**

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Membuat pipeline dengan TfidfVectorizer dan Multinomial Naive Bayes
pipeline = Pipeline([
    ('vectorizer', TfidfVectorizer(stop_words='english')),
    ('classifier', MultinomialNB())
])

# Melatih model
pipeline.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer(stop_words='english')),
                ('classifier', MultinomialNB())])

**Evaluasi TF-IDF**

In [23]:
# Memprediksi label untuk data pengujian
y_pred = pipeline.predict(X_test)

# Mengukur akurasi model dengan TF-IDF
accuracy_tfidf = accuracy_score(y_test, y_pred)
print("Akurasi Model Multinomial Naive Bayes dengan TF-IDF:", accuracy_tfidf)

# Menampilkan hasil klasifikasi dengan TF-IDF
print("\nLaporan Klasifikasi dengan TF-IDF:")
print(classification_report(y_test, y_pred))

# Menampilkan matriks konfusi dengan TF-IDF
print("\nMatriks Konfusi dengan TF-IDF:")
print(confusion_matrix(y_test, y_pred))

Akurasi Model Multinomial Naive Bayes dengan TF-IDF: 0.9677033492822966

Laporan Klasifikasi dengan TF-IDF:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1453
           1       1.00      0.75      0.86       219

    accuracy                           0.97      1672
   macro avg       0.98      0.88      0.92      1672
weighted avg       0.97      0.97      0.97      1672


Matriks Konfusi dengan TF-IDF:
[[1453    0]
 [  54  165]]


**Kesimpulan**

Melihat dari hasil yg ada, beda akurasinya hanya beda sedikit namun CountVectorized lebih akurat.