## TUGAS PRAKTIKUM
1. Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
2. Anda diperbolehkan melakukan eksplorasi terhadap,
- Metode pra pengolahan
- Pemilihan fitur
- Arsitektur ANN
- Fungsi Aktiviasi
3. ANN diimplementasikan dengan menggunakan tensowflow
4. DIKERJAKAN SECARA BERKELOMPOK
5. JELASKAN HASIL YANG ANDA DAPATKAN.
- AKURASI
- CONFUSION MATRIX
- KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

### Langkah 1 - Impor Library


In [4]:
import tensorflow as tf
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix, accuracy_score

In [7]:
from sklearn import datasets

# Load dataset MNIST
data_mnist = datasets.fetch_openml("mnist_784")

f:\POLINEMA\2B SEMESTER 5\Pembelajaran Mesin\Pembelajaran_Mesin2023\Week09V\myenv\Lib\site-packages\sklearn\datasets\_openml.py:1022: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


data_mnist = datasets.fetch_openml("mnist_784")

### Langkah 2 - Eksplorasi Dataset

In [8]:
# Melihat dimensi data
print("Jumlah sampel MNIST:", data_mnist.data.shape[0])  # Jumlah sampel
print("Dimensi setiap sampel MNIST:", data_mnist.data.shape[1])  # Dimensi setiap sampel
print("Jumlah kelas MNIST:", len(set(data_mnist.target)))  # Jumlah kelas

Jumlah sampel MNIST: 70000
Dimensi setiap sampel MNIST: 784
Jumlah kelas MNIST: 10


In [9]:
# mengambil data dan label
X = data_mnist.data.astype('float32')
y = data_mnist.target.astype('int')

In [10]:
X.shape

(70000, 784)

In [11]:
# scaling data menggunakan MinMaxScaler
scaler = MinMaxScaler()
X_scalling = scaler.fit_transform(X)

In [12]:
print(X_scalling[:5])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### Langkah 3 - Ekstraksi Fitur dan Split Data

In [13]:
pca = PCA(n_components=200)
X_pca = pca.fit_transform(X_scalling)

In [14]:
# Split dataset menjadi data pelatihan dan data pengujian
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size = 0.2, random_state = 42)

### Langkah 4 - Membangun Model ANN

In [15]:
# Membuat model ANN
model = Sequential()

# Tambahkan lapisan input
model.add(Dense(units=128, activation='relu', input_dim=200))  # 128 unit pada lapisan tersembunyi pertama

# Tambahkan lapisan tersembunyi pertama
model.add(Dense(units=64, activation='relu'))  # 64 unit pada lapisan tersembunyi kedua

# Tambahkan lapisan tersembunyi kedua
model.add(Dense(units=32, activation='relu'))  # 32 unit pada lapisan tersembunyi ketiga

# Tambahkan lapisan output
model.add(Dense(units=10, activation='softmax'))  # 10 unit pada lapisan output untuk klasifikasi 10 kelas

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               25728     
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 10)                330       
                                                                 
Total params: 36394 (142.16 KB)
Trainable params: 36394 (142.16 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### Langkah 5 - Training Model

In [16]:
# Kompilasi model ANN
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [17]:
# Melatih model menggunakan data pelatihan
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)  # Contoh menggunakan 10 epoch dan ukuran batch 32

# Evaluasi model menggunakan data pengujian
loss, accuracy = model.evaluate(X_test, y_test)
print("Loss:", loss)
print("Accuracy:", accuracy)

Epoch 1/10
1400/1400 [==============================] - 9s 4ms/step - loss: 0.3015 - accuracy: 0.9122 - val_loss: 0.1405 - val_accuracy: 0.9577
Epoch 2/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.1026 - accuracy: 0.9690 - val_loss: 0.1122 - val_accuracy: 0.9672
Epoch 3/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0660 - accuracy: 0.9796 - val_loss: 0.1108 - val_accuracy: 0.9655
Epoch 4/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0435 - accuracy: 0.9867 - val_loss: 0.1101 - val_accuracy: 0.9684
Epoch 5/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0311 - accuracy: 0.9902 - val_loss: 0.1069 - val_accuracy: 0.9693
Epoch 6/10
1400/1400 [==============================] - 5s 4ms/step - loss: 0.0230 - accuracy: 0.9921 - val_loss: 0.1332 - val_accuracy: 0.9679
Epoch 7/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0201 - accuracy: 0.9930 - val_loss: 0.1144 - val_accuracy:

### Langkah 6 - Evaluasi

In [18]:
# Evaluasi model pada data pelatihan
train_loss, train_accuracy = model.evaluate(X_train, y_train)
print("Train Loss:", train_loss)
print("Train Accuracy:", train_accuracy)

1750/1750 [==============================] - 5s 3ms/step - loss: 0.0402 - accuracy: 0.9907
Train Loss: 0.040227919816970825
Train Accuracy: 0.9906785488128662


In [19]:
# Evaluasi model pada data pengujian
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

438/438 [==============================] - 1s 3ms/step - loss: 0.1603 - accuracy: 0.9666
Test Loss: 0.16030019521713257
Test Accuracy: 0.9665714502334595


In [21]:
# Melakukan prediksi menggunakan model pada data pengujian
predictions = model.predict(X_test)

# Mengubah prediksi dari format one-hot encoded ke kelas
predicted_classes = np.argmax(predictions, axis=1)

# Menghitung confusion matrix
confusion_mtx = confusion_matrix(y_test, predicted_classes)

print("Confusion Matrix:")
print(confusion_mtx)

438/438 [==============================] - 1s 3ms/step
Confusion Matrix:
[[1315    0    4    1    1    1    3    4   13    1]
 [   0 1566    8    1    3    0    0    4   18    0]
 [   0    3 1349    5    4    1    1    7    9    1]
 [   0    3   20 1369    0   12    0    9   14    6]
 [   1    1    5    0 1256    0    5    4   11   12]
 [   0    1    1   13    0 1237    6    1   12    2]
 [   4    1    3    0    4   12 1362    2    8    0]
 [   4    1   17    3    3    1    0 1460    4   10]
 [   2    5   16   11    2   14    3    6 1292    6]
 [   4    1    1   11   20   10    0   28   19 1326]]
