**Langkah 1-Import Library**

In [1]:
# Melakukan Import Library
import numpy as np
import pandas as pd
import tensorflow as tf

c:\Users\Hp\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


**Langkah 2-Load Data**

In [2]:
# Membaca data
dataset = pd.read_csv('Churn_Modelling.csv')

# Mengekstrak fitur yang akan digunakan untuk analisa
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [3]:
# Melakukan Pengecekkan data
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


**Langkah 3-Encoding Data Kategorikal**

In [4]:
# Melakukan import LabelEncoder
from sklearn.preprocessing import LabelEncoder
# Membuat variabel untuk menyimpan objek
le = LabelEncoder()
# Mengubah nilai dan menyimpannya dalam array x
X[:, 2] = le.fit_transform(X[:, 2])

In [5]:
# Melakukan Pengecekkan data
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


**Langkah 4-Encoding Kolom "Geography" dengan One Hot Encoder**

In [6]:
# Melakuka import
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Melakukan transformasi pada kolom data
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# Mengubah hasil transformasi menjadi array NumPy
X = np.array(ct.fit_transform(X))

In [7]:
# Melakukan Pengecekkan data
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


**Langkah 5-Split Data**

In [8]:
# Melakukan import
from sklearn.model_selection import train_test_split
# Membagi data menjadi 4 subset yang akan digunakan dalam proses pengujian dan pelatihan model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
# Melakukan Pengecekkan data
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


**Langkah 6-Scalling Fitur**

In [10]:
# Melakukan import
from sklearn.preprocessing import StandardScaler
# Membuat objek untuk mengukur skala data
sc = StandardScaler()
# Mengukur skala data pelatihan
X_train = sc.fit_transform(X_train)
# Mengukur skala data pengujian
X_test = sc.transform(X_test)

In [11]:
# Melakukan Pengecekkan data
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Membuat Model ANN

**Langkah 1- Inisialisasi Model ANN**

In [12]:
# Membuat objek yang disimpan dalam variabel
ann = tf.keras.models.Sequential()

**Langkah 2-Membuat Input Layer dan Hidden Layer Pertama**

In [13]:
# Menambahkan lapisan untuk membentuk rancangan jaringan model untuk layer pertama
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**Langkah 3-Membuat Hidden Layer Kedua**

In [14]:
# Menambahkan lapisan untuk membentuk rancangan jaringan model untuk layer kedua
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**Langkah 4-Membuat Output Layer**

In [15]:
# Menghasilkan prediksi model 
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training Model

**Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN**

In [16]:
# Melakukan kompilasi pada model 'ann' dengan mengukur sejauh mana predsiksi
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

**Langkah 2 - Fitting Model**

In [17]:
# Melatih model dengan mengatur jumlah epochs untuk meminimalisir kerugian
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5297 - accuracy: 0.7745
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4761 - accuracy: 0.7954
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4502 - accuracy: 0.7962
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.8010
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4192 - accuracy: 0.8062
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4050 - accuracy: 0.8134
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3907 - accuracy: 0.8195
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3785 - accuracy: 0.8298
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3696 - accuracy: 0.8428
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3631 - accura

**Modelkan Data Baru dan Buat Prediksi**

In [18]:
# Menampilkan output prediksi model berupa true atau false
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 122ms/step
[[False]]


**Prediksi Dengan Data Testing**

In [19]:
# Membuat prediksi data pengujian
y_pred = ann.predict(X_test)
# Mengubah hasil prediksi menjadi biner
y_pred = (y_pred > 0.5)
# Mencetak kemungkinan sejauh mana prediksi
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


**Cek Akurasi dan Confunsion Matrix**

In [20]:
# Melakukan import
from sklearn.metrics import confusion_matrix, accuracy_score
# Menghitung matriks konfusi dengan membandingkan 2 label
cm = confusion_matrix(y_test, y_pred)
# Mencetak matriks konfusi
print(cm)
# Menghitung akurasi matriks
accuracy_score(y_test, y_pred)

[[1497   98]
 [ 189  216]]


0.8565