# Tugas

- Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
- Anda diperbolehkan melakukan eksplorasi terhadap,
    - Metode pra pengolahan
    - Pemilihan fitur
    - Arsitektur ANN
    - Fungsi Aktiviasi
- ANN diimplementasikan dengan menggunakan tensorflow.
- **DIKERJAKAN SECARA BERKELOMPOK**
- **JELASKAN HASIL YANG ANDA DAPATKAN,**
    - **AKURASI**
    - **CONFUSION MATRIX**
    - **KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN** **SAMPAI ARSITEKTUR ANN**

**Langkah 1 - Import Library**

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

**Langkah 2 - Pra-pengolahan data MNIST**

Jika error, run lagi

In [3]:
# Pra-pengolahan data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data() # load data MNIST dan split data

# ubah bentuk fitur menjadi vektor dan dinormalisasi
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0

11490434/11490434 [==============================] - 7s 1us/step


**Langkah 3 - Buat Arsitektur ANN**

In [4]:
# Arsitektur ANN
# Terdiri dari 3 lapisan Dense dengan funsi aktivasi ReLU
ann = keras.Sequential(
    [
        layers.Dense(256, activation="relu"),
        layers.Dense(128, activation="relu"),
        layers.Dense(10),
    ]
)

**Langkah 4 - Buat Fugsi Aktivasi**

In [5]:
# Fungsi aktivasi
ann.compile(
    optimizer=keras.optimizers.Adam(0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

**Langkah 5 - Latih Model ANN dan Lakukan Evaluasi Model**

In [6]:
# Pelatihan model
# Model dilatih menggunakan data latih dengan batch size 32 dan epoch sebanyak 5 kali.
ann.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)

# Evaluasi model
# Model dievaluasi menggunakan data uji dan menghitung akurasi.
test_loss, test_acc = ann.evaluate(x_test, y_test, verbose=2)
print("Test accuracy:", test_acc)

Epoch 1/5
1875/1875 - 6s - loss: 0.2054 - accuracy: 0.9392 - 6s/epoch - 3ms/step
Epoch 2/5
1875/1875 - 6s - loss: 0.0857 - accuracy: 0.9728 - 6s/epoch - 3ms/step
Epoch 3/5
1875/1875 - 6s - loss: 0.0578 - accuracy: 0.9815 - 6s/epoch - 3ms/step
Epoch 4/5
1875/1875 - 5s - loss: 0.0425 - accuracy: 0.9862 - 5s/epoch - 3ms/step
Epoch 5/5
1875/1875 - 6s - loss: 0.0357 - accuracy: 0.9884 - 6s/epoch - 3ms/step
313/313 - 1s - loss: 0.0895 - accuracy: 0.9759 - 811ms/epoch - 3ms/step
Test accuracy: 0.9758999943733215


**Langkah 6 - Tampilkan Confusion Matrix**

In [7]:
# Confusion matrix
# Confusion matrix dihitung menggunakan data uji dan prediksi model.
y_pred = ann.predict(x_test)
confusion_matrix = tf.math.confusion_matrix(y_test, tf.argmax(y_pred, axis=1))
print("Confusion matrix:\n", confusion_matrix)

313/313 [==============================] - 1s 2ms/step
Confusion matrix:
 tf.Tensor(
[[ 974    0    0    2    0    0    1    1    2    0]
 [   0 1126    3    1    0    0    3    0    2    0]
 [   5    1 1014    5    2    0    1    4    0    0]
 [   0    0    3  997    0    2    0    4    2    2]
 [   0    1    1    0  967    0    5    1    0    7]
 [   3    0    0   23    1  857    2    1    1    4]
 [  13    2    3    1    5    3  931    0    0    0]
 [   1   11   14    2    1    0    0  992    2    5]
 [   5    1    8   12    7    1    2    5  931    2]
 [   4    5    1    4   18    1    0    5    1  970]], shape=(10, 10), dtype=int32)
