# TUGAS PRAKTIKUM

1. Buatlah model klasifikasi dengan menggunakan SVM untuk data suara, voice.csv. 

In [1]:
# Langkah 1: Muat data dari file CSV

import numpy as np
import pandas as pd

data = pd.read_csv('voice.csv')
data.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [2]:
# Langkah 2: Persiapan data
X = data.drop('label', axis=1)  # Fitur-fitur
y = data['label']  # Label
     

In [3]:
# Pisahkan data menjadi data pelatihan (X_train, y_train) dan data pengujian (X_test, y_test)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

# Langkah 3: Preprocessing data

# 1. Penanganan Nilai Hilang (jika diperlukan)
imputer = SimpleImputer(strategy='mean')  # Gantilah dengan strategi yang sesuai
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

# 2. Encoding Label (jika diperlukan)
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

# 3. Normalisasi atau Standarisasi (jika diperlukan)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [6]:
from sklearn.svm import SVC

# Langkah 4: Buat model SVM
svm_model = SVC(kernel='linear')  # Atur kernel sesuai kebutuhan

# Langkah 5: Latih model pada data pelatihan
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
svm_model.fit(X_train, y_train)

SVC(kernel='linear')

In [7]:
from sklearn.metrics import accuracy_score

# Langkah 6: Evaluasi model
y_pred = svm_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi model SVM:", accuracy)

Akurasi model SVM: 0.9416403785488959


2. Buatlah model klasfikasi Multinomial Naive Bayes dengan ketentuan,
    1. Menggunakan data spam.csv
    2. Fitur CountVectorizer dengan mengaktifkan stop_words
    3. Evaluasi hasilnya

In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


df = pd.read_csv('spam.csv', encoding='latin-1') # spesifiksi encoding diperlukan karena data tidak menggunakan UTF-8

df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [9]:
# Mempersiapkan Data: Pisahkan kolom teks pesan dan kolom label ("spam" atau "ham").

X = df["v2"]
y = df["v1"]


In [10]:
#Pembagian Data: Bagi data menjadi data pelatihan (training) dan data pengujian (testing) menggunakan train_test_split.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [11]:
#Ekstraksi Fitur
#Gunakan CountVectorizer untuk mengonversi teks pesan menjadi vektor fitur.
#Stop words juga diaktifkan untuk mengabaikan kata-kata umum.

vectorizer = CountVectorizer(stop_words="english")
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

     

In [12]:
#Membuat Model: Buat model klasifikasi Multinomial Naive Bayes.
naive_bayes = MultinomialNB()


#Melatih Model : Latih model menggunakan data pelatihan yang sudah diubah menjadi vektor fitur.
naive_bayes.fit(X_train_vec, y_train)


MultinomialNB()

In [13]:
#Evaluasi Model
#Gunakan model yang telah dilatih untuk membuat prediksi pada data pengujian dan hitung akurasi serta laporan klasifikasi.

y_pred = naive_bayes.predict(X_test_vec) #Melakukan Prediksi dengan Model

#Menghitung Akurasi Model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi Model:", accuracy)

#Menghasilkan Laporan Klasifikasi
report = classification_report(y_test, y_pred)
print("Laporan Klasifikasi:\n", report)

#Menghasilkan Matriks Kebingungan (Confusion Matrix)
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion)

     

Akurasi Model: 0.9838565022421525
Laporan Klasifikasi:
               precision    recall  f1-score   support

         ham       0.99      0.99      0.99       965
        spam       0.96      0.92      0.94       150

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

Confusion Matrix:
 [[959   6]
 [ 12 138]]


3. Buatlah model klasfikasi Multinomial Naive Bayes dengan ketentuan,
    1. Menggunakan data spam.csv
    2. Fitur TF-IDF dengan mengaktifkan stop_words
    3. Evaluasi hasilnya dan bandingkan dengan hasil pada Tugas no 2.
    4. Berikan kesimpulan fitur mana yang terbaik pada kasus data spam.csv

In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv('spam.csv', encoding='latin-1') # spesifiksi encoding diperlukan karena data tidak menggunakan UTF-8

df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [2]:
# Preprocessing data (bersihkan kolom-kolom yang tidak diperlukan)
df = df[['v1', 'v2']]
df = df.rename(columns={'v1': 'label', 'v2': 'text'})

In [5]:
# Bagi data menjadi data latih dan data uji
X = df['text']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
# Inisialisasi TF-IDF Vectorizer dengan stop_words
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

# Transformasi teks menjadi vektor fitur TF-IDF
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [7]:
# Inisialisasi model Multinomial Naive Bayes
naive_bayes = MultinomialNB()

# Latih model pada data pelatihan
naive_bayes.fit(X_train_tfidf, y_train)

# Prediksi label pada data pengujian
y_pred = naive_bayes.predict(X_test_tfidf)

In [8]:
# Evaluasi hasil
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [9]:
# Menampilkan hasil
print("Akurasi:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Akurasi: 0.9668161434977578
Confusion Matrix:
 [[965   0]
 [ 37 113]]
Classification Report:
               precision    recall  f1-score   support

         ham       0.96      1.00      0.98       965
        spam       1.00      0.75      0.86       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.96      1115



Evaluasi dengan CountVectorizer

In [10]:
# Lakukan langkah-langkah pemodelan dengan CountVectorizer seperti yang telah Anda lakukan pada Tugas no 2
# Hitung akurasi, matriks kebingungan, dan laporan klasifikasi

# Contoh:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# Inisialisasi CountVectorizer dan model Multinomial Naive Bayes
count_vectorizer = CountVectorizer(stop_words='english')
X_train_count = count_vectorizer.fit_transform(X_train)
X_test_count = count_vectorizer.transform(X_test)
naive_bayes_count = MultinomialNB()
naive_bayes_count.fit(X_train_count, y_train)
y_pred_count = naive_bayes_count.predict(X_test_count)

# Evaluasi hasil
accuracy_count = accuracy_score(y_test, y_pred_count)
conf_matrix_count = confusion_matrix(y_test, y_pred_count)
class_report_count = classification_report(y_test, y_pred_count)

# Tampilkan hasil
print("Evaluasi dengan CountVectorizer:")
print("Akurasi:", accuracy_count)
print("Confusion Matrix:\n", conf_matrix_count)
print("Classification Report:\n", class_report_count)


Evaluasi dengan CountVectorizer:
Akurasi: 0.9838565022421525
Confusion Matrix:
 [[959   6]
 [ 12 138]]
Classification Report:
               precision    recall  f1-score   support

         ham       0.99      0.99      0.99       965
        spam       0.96      0.92      0.94       150

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



Evaluasi dengan TF-IDF Vectorizer

In [11]:
# Lakukan langkah-langkah pemodelan dengan TF-IDF Vectorizer seperti yang telah Anda lakukan pada Tugas no 3
# Hitung akurasi, matriks kebingungan, dan laporan klasifikasi

# Contoh:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

# Inisialisasi TF-IDF Vectorizer dan model Multinomial Naive Bayes
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)
naive_bayes_tfidf = MultinomialNB()
naive_bayes_tfidf.fit(X_train_tfidf, y_train)
y_pred_tfidf = naive_bayes_tfidf.predict(X_test_tfidf)

# Evaluasi hasil
accuracy_tfidf = accuracy_score(y_test, y_pred_tfidf)
conf_matrix_tfidf = confusion_matrix(y_test, y_pred_tfidf)
class_report_tfidf = classification_report(y_test, y_pred_tfidf)

# Tampilkan hasil
print("Evaluasi dengan TF-IDF Vectorizer:")
print("Akurasi:", accuracy_tfidf)
print("Confusion Matrix:\n", conf_matrix_tfidf)
print("Classification Report:\n", class_report_tfidf)


Evaluasi dengan TF-IDF Vectorizer:
Akurasi: 0.9668161434977578
Confusion Matrix:
 [[965   0]
 [ 37 113]]
Classification Report:
               precision    recall  f1-score   support

         ham       0.96      1.00      0.98       965
        spam       1.00      0.75      0.86       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.96      1115



Dari pemodelan diatas,dapat disimpulkan perbandingannya,yaitu :

Akurasi model dengan fitur CountVectorize lebih tinggi daripada menggunakan fitur TF-IDF. Bisa disimpulkan fitur CountVectorizh baik untuk kasus ini, dan perbedaan akurasi tidak signifikan perlu diperhatikan pada bagian matriks kebingungan dan laporan mengevaluasi kinerja model.