install library tensorflow

In [1]:
pip install --upgrade pip

  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   - -------------------------------------- 0.1/2.1 MB 1.7 MB/s eta 0:00:02
   ---- ----------------------------------- 0.2/2.1 MB 3.0 MB/s eta 0:00:01
   ----------- ---------------------------- 0.6/2.1 MB 4.1 MB/s eta 0:00:01
   ------------------ --------------------- 1.0/2.1 MB 5.5 MB/s eta 0:00:01
   ----------------------- ---------------- 1.2/2.1 MB 6.0 MB/s eta 0:00:01
   --------------------------- ------------ 1.4/2.1 MB 5.3 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 6.0 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 5.3 MB/s eta 0:00:01
   -------------------------------------- - 2.0/2.1 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 

In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


Langkah 1 - Import Library

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

Langkah 2 - Load Data

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


Langkah 3 - Encoding Data Kategorikal

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


Langkah 5 - Split Data

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Langkah 6 - Scaling Fitur

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Membuat Model ANN

In [11]:
# inisiasi model ANN
ann = tf.keras.models.Sequential()

In [12]:
# input layer dan hidden layer pertama
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [13]:
# membuat hidden layer kedua
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [14]:
# Membuat Output Layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Training Model

In [15]:
# Compile Model (Menyatukan Arsitektur) ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [16]:
# Fitting Model
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 3s 4ms/step - loss: 0.6945 - accuracy: 0.6212
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5355 - accuracy: 0.7946
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4698 - accuracy: 0.8041
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4459 - accuracy: 0.8100
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4367 - accuracy: 0.8129
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4288 - accuracy: 0.8175
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4183 - accuracy: 0.8241
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4045 - accuracy: 0.8344
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3886 - accuracy: 0.8418
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3739 - accura

Membuat Prediksi

Modelkan Data Baru dan Buat Prediksi

In [17]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)   #hasilnya false karena prediksi < 0.5

1/1 [==============================] - 0s 221ms/step
[[False]]


Prediksi Dengan Data Testing

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Cek Akurasi dan Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1504   91]
 [ 191  214]]


0.859