**Deskripsi**

Pada praktikum kali ini, Anda diminta untuk membuat model ANN untuk mengklasifikasi potensi seorang customer akan meninggalkan perusahaan Anda atau tidak. Istirlah populer dari fenomena ini disebut sebagai 'churn'. Tingkat churn yang tinggi (chrun rate) akan berdampak tidak baik bagi perusahaan.

### Langkah 1 - Import Library

In [1]:
import numpy as np  # Mengimpor modul 'numpy' dan memberinya alias 'np'. NumPy digunakan untuk komputasi numerik.
import pandas as pd  # Mengimpor modul 'pandas' dan memberinya alias 'pd'. Pandas digunakan untuk analisis dan manipulasi data.
import tensorflow as tf  # Mengimpor modul 'tensorflow'. TensorFlow adalah pustaka yang digunakan untuk pengembangan dan pelatihan model jaringan saraf tiruan.

### langkah 2 - Load Data


In [2]:
# connect ke drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
# Membaca dataset dari file CSV dan menyimpannya ke dalam variabel 'dataset'.
dataset = pd.read_csv('/content/drive/MyDrive/ML/Churn_Modelling.csv')

X = dataset.iloc[:, 3:-1].values  # Mengekstrak fitur (X) dari dataset.
y = dataset.iloc[:, -1].values  # Mengekstrak label kelas (y) dari dataset.

# tampilkan
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


### langkah 3 - Encoding Data Kategorikal

In [4]:
# Mengimpor modul yang diperlukan
from sklearn.preprocessing import LabelEncoder  # Mengimpor modul 'LabelEncoder' dari 'sklearn.preprocessing'. Modul ini digunakan untuk mengkodekan variabel kategorikal menjadi numerik.

# Membuat objek LabelEncoder
le = LabelEncoder()  # Membuat objek 'le' dari kelas 'LabelEncoder'.

# Mengkodekan kolom ketiga (X[:, 2]) dari variabel kategorikal menjadi numerik
X[:, 2] = le.fit_transform(X[:, 2])  # Menggunakan objek 'le' untuk mengkodekan kolom ketiga dari 'X' menjadi nilai numerik. Hasilnya akan disimpan kembali di kolom ketiga 'X'.

# tampilkan
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### angkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [5]:
# Mengimpor modul yang diperlukan dari library Scikit-Learn
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Membuat objek ColumnTransformer untuk mengubah kolom data
# dengan indeks 1 (kolom kedua) menggunakan OneHotEncoder, dan mengizinkan kolom lainnya tetap tidak diubah ('passthrough')
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

# Menggunakan ColumnTransformer untuk mengubah data X, dan
# hasilnya disimpan dalam bentuk array numpy (X)
X = np.array(ct.fit_transform(X))

print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Langkah 5 -  Split Data

In [6]:
from sklearn.model_selection import train_test_split  # import library yang dibutuhkan untuk penggunaan sickit-learn
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)  # Melakukan spilt data test dan train

### Langkah 6 - Scaling Fitur

In [7]:
from sklearn.preprocessing import StandardScaler # Membantu dalam standarisasi fitur
sc = StandardScaler() # Membuat objek StandardScaler
X_train = sc.fit_transform(X_train) # melakukan standarisasi pada data uji X_train
X_test = sc.transform(X_test) # melakukan standarisasi pada data tes X_test

## Membuat Model ANN

### Langkah 1 - Inisiasi Model ANN

In [8]:
ann = tf.keras.models.Sequential() # Membuat model neural network Sequential

### Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama


In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # menambahkan sebuah layer fully connected, atau dikenal juga sebagai dense layer
# Fungsi aktivasi Rectified Linear Unit (ReLU) menghasilkan input secara langsung jika positif; jika tidak, menghasilkan nol.

### Langkah 3 - Membuat Hidden Layer Kedua

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Langkah 4 - Membuat Output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # menambahkan sebuah layer fully connected (dense layer)
# Fungsi aktivasi Sigmoid mengubah setiap nilai output menjadi nilai antara 0 dan 1, yang bisa diinterpretasikan sebagai probabilitas.

## Training Model

### Langkah 1 - Compile Model (Menyatukan Arsitektru) ANN

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) # Optimizer ADAM (Adaptive Moment Estimation) untuk memperbarui bobot
# binary_crossentropy, sebagai loss function untuk klasifikasi binari
# ‘accuracy’ sebagai metrik yang menghitung persentase prediksi

### Langkah 2 - Fitting Model

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) # Melatih model ANN

Epoch 1/100
250/250 [==============================] - 3s 4ms/step - loss: 0.5104 - accuracy: 0.7950
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4554 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4401 - accuracy: 0.7961
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4325 - accuracy: 0.8009
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4265 - accuracy: 0.8098
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4207 - accuracy: 0.8140
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4135 - accuracy: 0.8190
Epoch 8/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4039 - accuracy: 0.8285
Epoch 9/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3918 - accuracy: 0.8366
Epoch 10/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3802 - accura

## Membuat Prediksi
Diberikan informais sebagai berikut,


- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: 60000
- Number of Products: 2
- Does this customer have a credit card ? Yes
- Is this customer an Active Member: Yes
- Estimated Salary: $50000

Apakah customer tersebut perlu dipertahankan?

**Modelkan Data Baru dan Buat Prediksi**

In [14]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 163ms/step
[[False]]


### Prediksi Dengan Data Testing

In [15]:
y_pred = ann.predict(X_test) # melakukan prediksi nilai berdasarkan X_test
y_pred = (y_pred > 0.5) # digunakan dalam konteks klasifikasi biner ketika Anda ingin mengonversi nilai-nilai prediksi menjadi label kelas
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) # menggabungkan dan menampilkan 2 array

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Cek Akurasi dan Confison Matrix

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score # Berguna dalam menghitung akurasi skor dan confusion matrix
cm = confusion_matrix(y_test, y_pred) # menghitung confusion matrix berdasarkan hasil tes dan prediksi
print(cm) # menampilkan hasil confusion matrix
accuracy_score(y_test, y_pred) # menghitung dan menampilkan akurasi matrix berdasarkan hasil tes dan prediksi

[[1508   87]
 [ 189  216]]


0.862